"""tambah kolom session_id

Revision ID: 2f27bf9108d5
Revises: 001_initial
Create Date: 2026-06-02 21:06:25.966346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f27bf9108d5'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('session_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_chat_history_created_at'), 'chat_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.alter_column('predictions', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.alter_column('sentiment_analysis', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_sentiment_analysis_analyzed_at'), 'sentiment_analysis', ['analyzed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_analysis_analyzed_at'), table_name='sentiment_analysis')
    op.alter_column('sentiment_analysis', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.alter_column('predictions', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_created_at'), table_name='chat_history')
    op.drop_column('chat_history', 'session_id')
    # ### end Alembic commands ###