"""cek perubahan schema

Revision ID: 9e881bb9a222
Revises: 2f27bf9108d5
Create Date: 2026-06-03 23:00:00.740566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e881bb9a222'
down_revision: Union[str, None] = '2f27bf9108d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###